### ISSUE TITLE
Error with emodnet_get_wfs_info(service = "physics")

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#129]
I am investigating now.

``` r
EMODnetWFS::emodnet_get_wfs_info(service = "physics")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> Loading IANA mime types...
#> No encoding supplied: defaulting to UTF-8.
#> ✔ WFS client created successfully
#> ℹ Service: 'https://geoserver.emodnet-physics.eu/geoserver/emodnet/wfs'
#> ℹ Version: '2.0.0'
#> Space required after the Public Identifier
#> SystemLiteral " or ' expected
#> SYSTEM or PUBLIC, the URI is missing
#> Error in `purrr::map_chr()`:
#> ℹ In index: 83.
#> Caused by error:
#> ! 1: Space required after the Public Identifier
#> 2: SystemLiteral " or ' expected
#> 3: SYSTEM or PUBLIC, the URI is missing

#> Backtrace:
#>      ▆
#>   1. ├─EMODnetWFS (local) `<fn>`(service = "physics")
#>   2. │ ├─... %>% ... at EMODnetWFS/R/info.R:50:2
#>   3. │ └─tibble::tibble(...)
#>   4. │   └─tibble:::tibble_quos(xs, .rows, .name_repair)
#>   5. │     └─rlang::eval_tidy(xs[[j]], mask)
#>   6. ├─tidyr::separate(...)
#>   7. ├─purrr::map_chr(capabilities$getFeatureTypes(), guess_layer_format)
#>   8. │ └─purrr:::map_("character", .x, .f, ..., .progress = .progress)
#>   9. │   ├─purrr:::with_indexed_errors(...)
#>  10. │   │ └─base::withCallingHandlers(...)
#>  11. │   ├─purrr:::call_with_cleanup(...)
#>  12. │   └─EMODnetWFS (local) .f(.x[[i]], ...)
#>  13. │     └─layer$getDescription(pretty = TRUE) at EMODnetWFS/R/info.R:103:2
#>  14. │       └─WFSDescribeFeatureType$new(...)
#>  15. │         └─ows4R (local) initialize(...)
#>  16. │           └─self$execute()
#>  17. │             └─private$GET(...)
#>  18. │               └─XML::xmlParse(text)
#>  19. ├─XML (local) `<fn>`(`<chr>`)
#>  20. │ └─base::stop(e)
#>  21. └─purrr (local) `<fn>`(`<XMLPrsEL>`)
#>  22.   └─cli::cli_abort(...)
#>  23.     └─rlang::abort(...)
```

<sup>Created on 2023-01-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by maelle** [comment]
it happens in

```r
purrr::map_chr(capabilities$getFeatureTypes(), guess_layer_format)
```

**Comment by maelle** [comment]
The problem is `getDescription()` for the layer ""emodnet:Registry of continuous noise monitoring sites""

**Comment by maelle** [comment]
@salvafern ideally in this case I should be looking into the actual XML served for that layer. Do you happen to remember how to do that?

**Comment by maelle** [comment]
Found the URL https://geoserver.emodnet-physics.eu/geoserver/emodnet/wfs?request=GetCapabilities

**Comment by maelle** [comment]
Comparing XML of that layer with that of the layer before it

```xml
</FeatureType>
<FeatureType>
<Name>emodnet:PSMSL_Region</Name>
<Title>PSMSL_Region</Title>
<Abstract/>
<ows:Keywords>
<ows:Keyword>features</ows:Keyword>
<ows:Keyword>PSMSL_Region</ows:Keyword>
</ows:Keywords>
<DefaultCRS>urn:ogc:def:crs:EPSG::4326</DefaultCRS>
<ows:WGS84BoundingBox>
<ows:LowerCorner>-179.99999999999994 -55.98402786254877</ows:LowerCorner>
<ows:UpperCorner>180.0 83.11042022705084</ows:UpperCorner>
</ows:WGS84BoundingBox>
<MetadataURL xlink:href="https://catalogue.emodnet-physics.eu/geonetwork/srv/eng/xml_iso19139?uuid=c044963aafd69f9a4c55f9fae5e112baee7d622a"/>
</FeatureType>
<FeatureType>
<Name>
emodnet:Registry of continuous noise monitoring sites
</Name>
<Title>Registry of continuous noise monitoring sites</Title>
<Abstract/>
<ows:Keywords>
<ows:Keyword>features</ows:Keyword>
<ows:Keyword>noise_fixed_platforms</ows:Keyword>
</ows:Keywords>
<DefaultCRS>urn:ogc:def:crs:EPSG::4326</DefaultCRS>
<ows:WGS84BoundingBox>
<ows:LowerCorner>-3.536 36.93</ows:LowerCorner>
<ows:UpperCorner>30.6 68.91</ows:UpperCorner>
</ows:WGS84BoundingBox>
</FeatureType>
<FeatureType>
<Name>emodnet:EP_GEO_WSEA_OTHR_NN_GR_EUR</Name>
<Title>
World Sea Atlas - Reference for European Sea Basins
</Title>
<Abstract>
World Sea Atlas - Reference for European Sea Basins
</Abstract>
<ows:Keywords>
<ows:Keyword>Oceanographic geographical features</ows:Keyword>
</ows:Keywords>
<DefaultCRS>urn:ogc:def:crs:EPSG::4326</DefaultCRS>
<ows:WGS84BoundingBox>
<ows:LowerCorner>-180.0 -85.47029103625539</ows:LowerCorner>
<ows:UpperCorner>180.0 90.0</ows:UpperCorner>
</ows:WGS84BoundingBox>
<MetadataURL xlink:href="https://catalogue.emodnet-physics.eu/geonetwork/srv/eng/xml_iso19139?uuid=2d739cd246570a8e6c03216c49058230d13c5c66"/>
</FeatureType>
```

**Comment by maelle** [comment]
or rather https://geoserver.emodnet-physics.eu/geoserver/emodnet/wfs?request=DescribeFeatureType :thinking:

**Comment by maelle** [comment]
Contrary to "emodnet:Registry of continuous noise monitoring sites" all other names have no space and no line return. I'm a bit out of my depth though. @salvafern do you think we should report this to the service maintainer?

**Comment by maelle** [comment]
@salvafern any insight?

**Comment by salvafern** [comment]
Sorry for the delay! I think the spaces are indeed the issue. The resulting GML is not valid:

https://geoserver.emodnet-physics.eu/geoserver/emodnet/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=emodnet%3ARegistry%20of%20continuous%20noise%20monitoring%20sites&maxFeatures=50

> XML Parsing Error: not well-formed
Location: https://geoserver.emodnet-physics.eu/geoserver/emodnet/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=emodnet%3ARegistry%20of%20continuous%20noise%20monitoring%20sites&maxFeatures=50
Line Number 1, Column 757:


Part of the resulting `gml `file where the problem starts:

```xml
<gml:featureMember>
	<emodnet:Registry of continuous noise monitoring sites fid="noise_fixed_platforms-fid1">
		<emodnet:country>DENMARK</emodnet:country>
		<emodnet:institution>Aarhus University, Department of Bioscience (BIOS)</emodnet:institution>
		<emodnet:institution_url>https://ecos.au.dk/en/</emodnet:institution_url>
		<emodnet:EDMO_code>5123</emodnet:EDMO_code>
		<emodnet:reference_url>https://www.ices.dk/data/data-portals/Pages/Continuous-Noise.aspx</emodnet:reference_url>
		<emodnet:data_source>ICES</emodnet:data_source>
		<emodnet:station_code_surce>12865</emodnet:station_code_surce>
		<emodnet:location>
			<gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
				<gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">14.46726667,54.79</gml:coordinates>
			</gml:Point>
		</emodnet:location>
	</emodnet:Registry>
</gml:featureMember>
```

GML thinks the tag is <emodnet:Registry> instead of the full name. Funny enough you can request other file extensions and these seem to work fine (tested `csv` and `shp`)

Yes, we have to report back :) 

@tim-collart Could you have a look or point to the responsible person for the EMODnet Physics geoserver?

**Comment by tim-collart** [comment]
Hi @salvafern,

Thanks for flagging. Three things:
1) Your question is indeed something that should be taken up with physics as they manage the GeoServer that produces the error. Now that EMODnet has centralized, all queries regarding it's data and service can go to secretariat@emodnet.ec.europa.eu. It will then get into our ticketing system and be assigned to the relevant person from Physics
2) The service you are using (https://geoserver.emodnet-physics.eu/geoserver/emodnet/ows) is an old one, with the current production service being located at https://prod-geoserver.emodnet-physics.eu/ as per https://github.com/EMODnet/Web-Service-Documentation. As such, I am not sure if they are still active maintaining the old service. Nevertheless you can still submit your question and see what they respond.
3) Regarding the updating of the services. I remember an earlier query you had regarding dynamically fetching an updated list of the services, rather than hardcoding them. Now that we are centralized, we have collected all metadata in a single catalogue:  https://emodnet.ec.europa.eu/geonetwork which you can access through a number of different API's. Many portals have also been including service metadata records in this catalogue, so it may now be possible to generate a list of services, parsing the service metadata records through the API.

Best wishes,
Tim

**Comment by maelle** [comment]
@salvafern I'm going to work on a PR to use 3. and 2.
@tim-collart thanks a ton!

**Comment by maelle** [comment]
@tim-collart I'm a bit lost trying to generate the list of all WFS services through the link you provided I tried a few combinations. We need a list of service names (for instance "chemistry_cdi_data_discovery_and_access_service") and URLs (for instance https://geo-service.maris.nl/emodnet_chemistry/wfs)

https://emodnet.ec.europa.eu/geonetwork/emodnet/eng/catalog.search#/search?facet.q=type%2FOGC%253AWFS&resultType=details&sortBy=sortDate&fast=index&_content_type=json&from=1&to=20 does not seem to contain all services, for instance not the geology ones.

Do you have an example? Thank you!

**Comment by salvafern** [comment]
@maelle @tim-collart I have reported the issue with this layer to EMODnet

**Comment by salvafern** [comment]
Hi @tim-collart, same as @maelle I cannot find a way via geonetwork to list all the OGC endpoints, or at least WFS and WCS. 

Could you suggest what filter to apply to get to such a list? Thank you!

**Comment by salvafern** [comment]
Solved in: https://github.com/EMODnet/EMODnetWFS/pull/131
Continue in: https://github.com/EMODnet/EMODnetWFS/issues/139
