### ISSUE TITLE
Wrong bathymetry results following tutorial

### ISSUE THREAD

**Issue by teuzindahuz** [EMODnet/EMODnetWFS#13]
Following the [tutorial](https://www.emodnet.eu/conference/opensealab/sites/opensealab.eu/files/public/2019/data/OSLII_R_Tutorial_EMODnet.html#6_search_for_data_using_emodnet_catalogue_service), the "getbathymetry" function results in a wrong raster, which provides the altitudinal values, instead of the bathymethrycal. In fact, it seems that the bathymetry is masked with values of 0s. I think that the error is given by the "name" parameter. If it is changed to "emodnet:mean_2016", the resulting raster is correct, but then I cannot plot it.

**Comment by LennertSchepers** [comment]
Dear @teuzindahuz, thanks for your feedback.
You are referring to a tutorial for the OpenSeaLab Hackathon in 2019, so it might be that there have been some changes since.
@tim-collart has an updated repository for the tutorials, the one for Biology is included in this jupyter notebook: https://github.com/EMODnet/Web-Service-Documentation/blob/main/R-tutorial/EMODnet_web_services_in_R_part1.ipynb
Does this help?

**Comment by teuzindahuz** [comment]
Ok, thanks, I'll look at that tutorial.
