### ISSUE TITLE
Get list of all OGC endpoints from catalog instead of hard-coded text file

### ISSUE THREAD

**Issue by salvafern** [EMODnet/EMODnetWFS#139]
Triggered by https://github.com/EMODnet/EMODnetWFS/issues/129
> Hi @tim-collart, same as @maelle I cannot find a way via geonetwork to list all the OGC endpoints, or at least WFS and WCS.
> 
> Could you suggest what filter to apply to get to such a list? Thank you!

Another option I can think of: get the list from https://github.com/EMODnet/Web-Service-Documentation/blob/main/README.md
Currently this is a table written as markdown. We would have to:
1. Turn into .Rmd
2. Turn tables with endpoints into csv files. Render into .md. 
3. EMODnetWFS would pull these csv files

**Comment by salvafern** [comment]
But honestly better to have a geonetwork / CWS catalog with all the endpoints and more info

**Comment by maelle** [comment]
smart workaround, though, if we end up needing it!

**Comment by maelle** [comment]
to parse the Markdown we could use Pandoc to convert it to HTML and then extract the table from there?

**Comment by salvafern** [comment]
Isn't that more work than just having the tables as csv? If @tim-collart agreed with that option of course

**Comment by salvafern** [comment]
Discussed with @maelle 2023-04-07: 

* [ ] Read the txt files with the endpoints from https://github.com/EMODnet/Web-Service-Documentation/tree/salvadorf-use_readme_rmd/data
* [ ] Create a back-up file in the package in case github fails. Potentially add a github action that checks whenever https://github.com/EMODnet/Web-Service-Documentation gets a new commit.

**Comment by maelle** [comment]
I'm thinking about another solution

- the first time an user uses the package, the txt file is downloaded to a local app dir.
- in every session, the cache is updated or, if GitHub is down, the cache is used with a warning.

The limitation is that GitHub has to be up at least once. I feel it's simpler though, because it allows the package to contain no copy.

As a workaround in case GitHub is down for a long time, we could set options (one for a different location for the txt file, one for a different location for the csv). I'll make a PR with this.

**Comment by maelle** [comment]
#153

**Comment by salvafern** [comment]
Talk with @maelle today: It's been a long time and no answer so far, so doesn't seem this will be a solution. Instead we may need to regularly monitor https://github.com/EMODnet/Web-Service-Documentation/ and manually update `emodnet_wfs()`
