### ISSUE TITLE
Human facing docs of the web services?

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#72]
That's something we need, especially before submitting the package to rOpenSci.

**Comment by maelle** [comment]
https://emodnet.ec.europa.eu/en/data linked in the README is broken.

**Comment by maelle** [comment]
I see https://emodnet.ec.europa.eu/en/emodnet-web-service-documentation#inline-nav-3

**Comment by maelle** [comment]
> WFS supports a variety of WFS output formats (Ex: GML, shapefile, json, geojson, CSV,...)

**Comment by maelle** [comment]
At the bottom of that page there are links to docs such as https://www.emodnet-biology.eu/emodnet-biology-api

**Comment by maelle** [comment]
I've read https://www.emodnet-biology.eu/emodnet-biology-api and it mentions less layers than what we get via the package.

**Comment by maelle** [comment]
The ones that have an abstract  via `emodnet_get_wfs_info()` are the ones that are described in the human facing docs.

**Comment by maelle** [comment]
Should we advise users to make sure they read the human-facing docs, or can we fear these get out of sync?

**Comment by salvafern** [comment]
This is happening because of the EMODnet migration to the europa.eu domain, it is likely that the links break, but the central portal maintains the documentation updated (although not redirecting the old link to the new one...) and VLIZ maintains the EMODnet-Biology webservice documentation, which will also be moved, no idea when tho. 

At least in biology, not all layers are intended to be useful for users - some of them are needed for the infrastructure of the download toolbox. Not sure the exact purpose of all of them tho, we can ask. The ones described in the docs are the important ones to get occurrence data (and the ones being used both by the download toolbox and the eurobis R package). 

> Should we advise users to make sure they read the human-facing docs, or can we fear these get out of sync?

Yes! They should read the docs.

**Comment by maelle** [comment]
:wave: @salvafern, is there now a general link we should point users to when they look for human facing docs of the web services? Thank you. :smile_cat:

**Comment by salvafern** [comment]
Hi @maelle , sorry for the late reply! 

Still this is the main general link with documentation of the web services: https://emodnet.ec.europa.eu/en/emodnet-web-service-documentation

The EMODnet Central Portal team is currently busy with the migration of the thematic lots. In the following months there should be more clarity - or we will be able to ask them for better documentation.

**Comment by maelle** [comment]
Thank you @salvafern!!
